version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  huggingface-inference-endpoints: {}

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/


workflows:
  test-deploy:
    jobs:
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: circleci/huggingface-inference-endpoints
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
          context: Circleci-Ai-Orb-Publishing
          filters: *release-filters
